### ISSUE TITLE
Methods should have a return type

### ISSUE THREAD

**Issue by sgon00** [huuang/lunar_calendar_converter#2]
Thank you very much for this project again. Very helpful. This is the first lunar support in Dart and works well in Flutter too. 

I would just suggest add return types to all methods. Otherwise, their return type will be `dynamic` by default. 

For example, 

LunarSolarConverter's methods `lunarToSolar`, `solarToLunar`, and even the private methods `_getBitInt` etc..

Solar's `solarYear` getter and setter etc.. and the `toString()` is better to be 

```
@override
String toString()
```

Thank you very much for this package again.

**Comment by huuang** [comment]
Thank you for your suggestion, I have updated the library.

sgon00 <notifications@github.com> 于2019年5月19日周日 下午5:04写道：

**Comment by sgon00** [comment]
👍😀Cool, thanks a lot for the update. Closing this issue.
